package com.h5.framework.server.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseEmailAuthToken<M extends BaseEmailAuthToken<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setUserId(java.lang.Long userId) {
		set("user_id", userId);
	}

	public java.lang.Long getUserId() {
		return get("user_id");
	}

	public void setEmail(java.lang.String email) {
		set("email", email);
	}

	public java.lang.String getEmail() {
		return get("email");
	}

	public void setToken(java.lang.String token) {
		set("token", token);
	}

	public java.lang.String getToken() {
		return get("token");
	}

	public void setType(java.lang.Integer type) {
		set("type", type);
	}

	public java.lang.Integer getType() {
		return get("type");
	}

	public void setIsVerify(java.lang.Integer isVerify) {
		set("is_verify", isVerify);
	}

	public java.lang.Integer getIsVerify() {
		return get("is_verify");
	}

	public void setValidAt(java.lang.Long validAt) {
		set("valid_at", validAt);
	}

	public java.lang.Long getValidAt() {
		return get("valid_at");
	}

	public void setCreateAt(java.lang.Long createAt) {
		set("create_at", createAt);
	}

	public java.lang.Long getCreateAt() {
		return get("create_at");
	}

	public void setVerifyAt(java.lang.Long verifyAt) {
		set("verify_at", verifyAt);
	}

	public java.lang.Long getVerifyAt() {
		return get("verify_at");
	}

}
