package com.h5.framework.server.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserPasswordRecord<M extends BaseUserPasswordRecord<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setUserId(java.lang.String userId) {
		set("user_id", userId);
	}

	public java.lang.String getUserId() {
		return get("user_id");
	}

	public void setPasswordDes(java.lang.String passwordDes) {
		set("password_des", passwordDes);
	}

	public java.lang.String getPasswordDes() {
		return get("password_des");
	}

	public void setPasswordMd5(java.lang.String passwordMd5) {
		set("password_md5", passwordMd5);
	}

	public java.lang.String getPasswordMd5() {
		return get("password_md5");
	}

	public void setCreateAt(java.lang.Long createAt) {
		set("create_at", createAt);
	}

	public java.lang.Long getCreateAt() {
		return get("create_at");
	}

}
