package com.h5.framework.server.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseArticleCommentReply<M extends BaseArticleCommentReply<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setCommentId(java.lang.Long commentId) {
		set("comment_id", commentId);
	}

	public java.lang.Long getCommentId() {
		return get("comment_id");
	}

	public void setReceiveUserId(java.lang.Long receiveUserId) {
		set("receive_user_id", receiveUserId);
	}

	public java.lang.Long getReceiveUserId() {
		return get("receive_user_id");
	}

	public void setReplyUserId(java.lang.Long replyUserId) {
		set("reply_user_id", replyUserId);
	}

	public java.lang.Long getReplyUserId() {
		return get("reply_user_id");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}

	public java.lang.String getContent() {
		return get("content");
	}

	public void setCreateAt(java.lang.Long createAt) {
		set("create_at", createAt);
	}

	public java.lang.Long getCreateAt() {
		return get("create_at");
	}

}
