package com.h5.framework.server.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseEmailSend_record<M extends BaseEmailSend_record<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}

	public java.lang.String getTitle() {
		return get("title");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}

	public java.lang.String getContent() {
		return get("content");
	}

	public void setSender(java.lang.Long sender) {
		set("sender", sender);
	}

	public java.lang.Long getSender() {
		return get("sender");
	}

	public void setSenderEmail(java.lang.String senderEmail) {
		set("sender_email", senderEmail);
	}

	public java.lang.String getSenderEmail() {
		return get("sender_email");
	}

	public void setReciver(java.lang.Long reciver) {
		set("reciver", reciver);
	}

	public java.lang.Long getReciver() {
		return get("reciver");
	}

	public void setReciverEmail(java.lang.String reciverEmail) {
		set("reciver_email", reciverEmail);
	}

	public java.lang.String getReciverEmail() {
		return get("reciver_email");
	}

	public void setType(java.lang.Integer type) {
		set("type", type);
	}

	public java.lang.Integer getType() {
		return get("type");
	}

	public void setIdDelete(java.lang.Integer idDelete) {
		set("id_delete", idDelete);
	}

	public java.lang.Integer getIdDelete() {
		return get("id_delete");
	}

	public void setCreateAt(java.lang.Long createAt) {
		set("create_at", createAt);
	}

	public java.lang.Long getCreateAt() {
		return get("create_at");
	}

}
